site_name: FastStream SqlBroker
site_description: SqlBroker for FastStream
site_url: https://faststream.ag2.ai/sqlbroker/

repo_name: faststream-community/faststream-sqlbroker
repo_url: https://github.com/faststream-community/faststream-sqlbroker
edit_uri: blob/main/docs/docs/

docs_dir: docs

nav:
  - SqlBroker:
    - sqlbroker/index.md
    - Design and Features: sqlbroker/design.md
    - Tutorial: sqlbroker/tutorial.md
